name: Nex Deployment

on:
  push:
    branches: [production]
    
jobs:
  deploy:
    runs-on: ubutu-lastest
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/next-test
          git fetch origin
          git checkout production
          git pull
          npm install
          npm run build
          pm2 reload
